package players;

public enum SuperAbility {
    HEAL, CRITICAL_DAMAGE, BOOST, SAVE_DAMAGE_AND_REVERT, BIGGER_OR_SMALLER, HACK_AND_GIVE, GOLDEN_SHILD,
    GOLEM_POWER, SAVE_LIFE_HERO, SPAWN_CROW_OR_ANGEL,TO_SHOCK
}
